- set_fact: dir={{ dockerfile_directory }}/mariadb

- file: path={{ dir }} state=directory owner={{ os_admin_user }} group={{ os_admin_group }} mode=755
  become: yes

- template: src={{ item }}.j2 dest={{ dir }}/{{ item }} owner={{ os_admin_user }} group={{ os_admin_group }} mode=644
  with_items:
    - MariaDB.repo
    - entrypoint.sh
    - server.cnf
    - init.sql
    - Dockerfile
  become: yes

- command: docker build -t {{ docker_mariadb }} .
  args:
    chdir: "{{ dir }}"
  become: yes

- command: docker tag {{ docker_mariadb }} {{ docker_registry_domain }}:{{ docker_registry_port }}/{{ docker_mariadb }}
  become: yes

- command: docker push {{ docker_registry_domain }}:{{ docker_registry_port }}/{{ docker_mariadb }}
  become: yes
