- hosts: docker
  roles:
    - docker-registry
    - dockerfile-rabbitmq
    - dockerfile-scala-rabbitmq-test
    - dockerfile-mariadb
    - dockerfile-scala-mariadb-test
    - dockerfile-scala-grpc-test
