FROM {{ docker_java }}

RUN wget https://github.com/nokamoto/scala-grpc-test/releases/download/20160426/scala-grpc-test-client.jar

CMD java -Dhost=${GRPC_HOST} -Dport=${GRPC_PORT} -jar scala-grpc-test-client.jar
