- set_fact: dir={{ dockerfile_directory }}/rabbitmq

- file: path={{ dir }} state=directory owner={{ os_admin_user }} group={{ os_admin_group }} mode=755
  become: yes

- template: src={{ item }}.j2 dest={{ dir }}/{{ item }} owner={{ os_admin_user }} group={{ os_admin_group }} mode=644
  with_items:
    - rabbitmq.config
    - .erlang.cookie
    - Dockerfile
  become: yes

- command: docker build -t {{ docker_rabbitmq }} .
  args:
    chdir: "{{ dir }}"
  become: yes

- command: docker tag {{ docker_rabbitmq }} {{ docker_registry_domain }}:{{ docker_registry_port }}/{{ docker_rabbitmq }}
  become: yes

- command: docker push {{ docker_registry_domain }}:{{ docker_registry_port }}/{{ docker_rabbitmq }}
  become: yes
